import { ColorValue, StyleSheet } from 'react-native';

const colors = {
  background: '#0B0F14' as ColorValue,
  white: 'white' as ColorValue,
  shadow: '#000' as ColorValue,
  errorText: '#FFB3B3' as ColorValue,
  cardBackground: '#111827' as ColorValue,
} as const;

const alpha = {
  whiteTransparent: (opacity: number) => `rgba(255,255,255,${opacity})` as ColorValue,
  errorTransparent: (opacity: number) => `rgba(255,80,80,${opacity})` as ColorValue,
};

export const theme = {
  colors,
  alpha,
} as const;

export const useStyles = () =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: theme.colors.background },

    listContent: { padding: 16, paddingTop: 8, gap: 12 },
    listContentEmpty: { flexGrow: 1, justifyContent: 'center' },
    listHeader: { gap: 10 },
    draggableCard: { position: 'relative' },
    draggableCardActive: {
      zIndex: 10,
      shadowColor: theme.colors.shadow,
      shadowOpacity: 0.3,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 6 },
      elevation: 6,
    },

    loadingState: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 12,
    },
    loadingText: { color: theme.alpha.whiteTransparent(0.8), fontWeight: '600' },
    emptyState: { alignItems: 'center', gap: 8, paddingHorizontal: 32 },
    emptyTitle: { color: theme.colors.white, fontSize: 18, fontWeight: '800' },
    emptyBody: {
      color: theme.alpha.whiteTransparent(0.65),
      fontSize: 14,
      fontWeight: '600',
      textAlign: 'center',
    },
    errorState: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
      paddingHorizontal: 32,
    },
    errorTitle: { color: theme.colors.white, fontSize: 18, fontWeight: '800' },
    errorBody: {
      color: theme.alpha.whiteTransparent(0.65),
      fontSize: 14,
      fontWeight: '600',
      textAlign: 'center',
    },
    errorBanner: {
      backgroundColor: theme.alpha.whiteTransparent(0.06),
      borderRadius: 12,
      padding: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    errorBannerText: { color: theme.alpha.whiteTransparent(0.8), fontWeight: '600' },
    offlineBanner: {
      backgroundColor: theme.alpha.whiteTransparent(0.1),
      borderRadius: 12,
      padding: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    offlineBannerText: { color: theme.colors.white, fontWeight: '700' },
    retryButton: {
      paddingHorizontal: 18,
      paddingVertical: 10,
      borderRadius: 999,
      backgroundColor: theme.colors.white,
    },
    retryButtonSmall: {
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: theme.colors.white,
    },
    retryButtonPressed: { opacity: 0.8 },
    retryButtonText: { color: theme.colors.background, fontWeight: '800' },

    onboardingContainer: { flex: 1, padding: 20, gap: 16 },
    onboardingTitle: { color: theme.colors.white, fontSize: 24, fontWeight: '800' },
    onboardingSubtitle: {
      color: theme.alpha.whiteTransparent(0.7),
      fontSize: 15,
      fontWeight: '600',
    },
    onboardingError: {
      backgroundColor: theme.alpha.errorTransparent(0.12),
      borderRadius: 12,
      padding: 12,
    },
    onboardingErrorText: { color: theme.colors.errorText, fontWeight: '600' },
    onboardingLoading: { alignItems: 'center', gap: 12, paddingVertical: 24 },
    onboardingList: { gap: 12, paddingBottom: 24 },
    choiceRow: {
      backgroundColor: theme.alpha.whiteTransparent(0.06),
      borderRadius: 14,
      paddingHorizontal: 16,
      paddingVertical: 14,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    choiceRowSelected: {
      backgroundColor: theme.alpha.whiteTransparent(0.16),
    },
    choiceText: { color: theme.colors.white, fontSize: 16, fontWeight: '700' },
    choiceTag: {
      color: theme.alpha.whiteTransparent(0.6),
      fontSize: 12,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.6,
    },
    choiceTagActive: { color: theme.colors.white },
    teamGroup: { gap: 8 },
    teamGroupTitle: {
      color: theme.alpha.whiteTransparent(0.8),
      fontSize: 13,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      marginTop: 6,
    },
    teamGroupEmpty: {
      color: theme.alpha.whiteTransparent(0.55),
      fontSize: 13,
      fontWeight: '600',
      marginBottom: 4,
    },
    onboardingFooter: { marginTop: 'auto', paddingTop: 8 },
    onboardingFooterRow: {
      flexDirection: 'row',
      gap: 12,
      justifyContent: 'space-between',
    },
    primaryButton: {
      flex: 1,
      paddingVertical: 12,
      borderRadius: 999,
      backgroundColor: theme.colors.white,
      alignItems: 'center',
    },
    primaryButtonDisabled: { backgroundColor: theme.alpha.whiteTransparent(0.4) },
    primaryButtonPressed: { opacity: 0.85 },
    primaryButtonText: { color: theme.colors.background, fontWeight: '800' },
    secondaryButton: {
      flex: 1,
      paddingVertical: 12,
      borderRadius: 999,
      backgroundColor: theme.alpha.whiteTransparent(0.08),
      alignItems: 'center',
    },
    secondaryButtonPressed: { opacity: 0.8 },
    secondaryButtonText: { color: theme.colors.white, fontWeight: '800' },

    settingsContent: { padding: 16, gap: 16, paddingBottom: 32 },
    settingsCard: {
      backgroundColor: theme.alpha.whiteTransparent(0.06),
      borderRadius: 14,
      padding: 16,
      gap: 12,
    },
    settingsCardTitle: { color: theme.colors.white, fontSize: 18, fontWeight: '800' },
    settingsSummaryText: {
      color: theme.alpha.whiteTransparent(0.7),
      fontSize: 14,
      fontWeight: '600',
    },
    settingsActionButton: {
      alignSelf: 'flex-start',
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 999,
      backgroundColor: theme.colors.white,
    },
    settingsActionButtonPressed: { opacity: 0.85 },
    settingsActionButtonText: { color: theme.colors.background, fontWeight: '800' },
    settingsToggleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    settingsToggleLabel: { color: theme.alpha.whiteTransparent(0.8), fontWeight: '600' },
    toggleButton: {
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 999,
      borderWidth: 1,
    },
    toggleButtonOn: {
      backgroundColor: theme.colors.white,
      borderColor: theme.colors.white,
    },
    toggleButtonOff: {
      backgroundColor: 'transparent' as ColorValue,
      borderColor: theme.alpha.whiteTransparent(0.3),
    },
    toggleButtonPressed: { opacity: 0.8 },
    toggleButtonDisabled: { opacity: 0.4 },
    toggleButtonText: { fontWeight: '800', fontSize: 12, letterSpacing: 0.4 },
    toggleButtonTextOn: { color: theme.colors.background },
    toggleButtonTextOff: { color: theme.alpha.whiteTransparent(0.75) },
    refreshControl: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    refreshValue: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 999,
      backgroundColor: theme.alpha.whiteTransparent(0.12),
    },
    refreshValueText: { color: theme.colors.white, fontWeight: '800' },
    refreshHint: { color: theme.alpha.whiteTransparent(0.6), fontWeight: '600' },
  });
